services:
  sciagi-app:
    build:
      context: .
      dockerfile: Dockerfile
    volumes:
      - ./:/app
    networks:
      - app-network
    restart: always

  nginx-proxy:
    image: nginx:alpine
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - ./nginx/conf.d:/etc/nginx/conf.d
      - ./nginx/ssl:/etc/nginx/ssl
      - ./static:/app/static
    depends_on:
      - sciagi-app
    networks:
      - app-network
    restart: always

networks:
  app-network:
    driver: bridge